---
language: ruby
rvm:
- 2.0.0
env:
  global:
  - secure: |-
      JpT5DR1eHjgt6v9W3/CbD0WrWJ5bQaiS6hxjiyRuZFml76nTkLeJsC9333eq
      kUPQDWPCqaDwnOe4qBvg8zMwVGPtBxDBbfu3AHNwQOfRIPqnfpOIJ59rXebT
      bFrX28dEy1G4w+mHwGZVHrchKlGDEXBt3zGJRMhkzL538ccRDjk=
  matrix:
  - LEARNERY_THEME=default
  - LEARNERY_THEME=railsgirls
  - LEARNERY_THEME=webdev
  - LEARNERY_THEME=coderdojo
before_install:
- ci/copytheme.sh
- ci/gitstatus.sh
script:
- rake
- bundle exec ruby ci/deploy.rb
